# Generated by Django 3.2 on 2021-07-09 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'verbose_name': 'Результат измерения', 'verbose_name_plural': 'Результаты измерения'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Объект на карте', 'verbose_name_plural': 'Объекты на карте'},
        ),
    ]
