# Generated by Django 3.2 on 2021-06-17 19:00
# Это применяется в том случае, если нам нужно загрузить какие-либо фикстурные данные в БД

from django.contrib.auth.models import User
from django.db import migrations


def add_admin(app, schema_editor):
    """
    Функция создаст в миграции нашего администратора.
    """
    user = User(
        id=1,
        username='admin',
        is_active=True,
        email='admin@email.com',
        is_staff=True,
        is_superuser=True
    )
    user.set_password('admin')
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]
    # обязательно здесь регистрируем нашу функцию
    operations = [
        migrations.RunPython(add_admin)
    ]
